spring.application.name=projectBookManagement



server.port=8085
spring.datasource.url=jdbc:mysql://localhost/sb_book1
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=create
